import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from "./providers";
import Nav from './components/nav'
import User from './components/user'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ERP',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <body className='h-screen'>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
